# Generated by Django 3.1.5 on 2021-03-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(blank='true', null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(blank='true', null='true'),
            preserve_default='true',
        ),
    ]
