# Generated by Django 3.1.5 on 2021-03-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210311_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
