# Generated by Django 3.1.5 on 2021-03-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210311_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
