# Generated by Django 3.1.5 on 2021-03-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='image/user/%Y/%m/%d'),
        ),
    ]
