# Generated by Django 3.1.5 on 2021-03-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.png', upload_to='image/post/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.png', upload_to='image/user/%Y/%m/%d'),
        ),
    ]
