# Generated by Django 3.1.5 on 2021-04-04 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_auto_20210404_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='requested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
