# Generated by Django 3.1.5 on 2021-04-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_chatbox_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
